FROM node:18

WORKDIR /usr/src/app

# Copy package files và cài đặt dependencies trước
COPY package*.json ./
RUN npm install

# Copy toàn bộ source code sau
COPY . .

EXPOSE 5000
CMD ["node", "server.js"]